SEO Optimise site description
compsci-adl/mytimetable pull request #33
Opened 2024-12-04 11:03 UTC by xxori

### Description
Including more keywords in meta description helps seo

### Changes Made
updated meta and og description in index.html

### Related Issues
*Reference any related issues using keywords like "Fixes #issue-number".*

### Additional Notes
*Add any other notes or screenshots that might be helpful for the reviewers.*

2024-12-04 11:08 UTC, xxori commented
# 🥺

2024-12-04 11:09 UTC, jsun969 approved these changes

2024-12-04 12:18 UTC, rayokamoto commented on index.html
Update `twitter:description` as well

2024-12-04 21:19 UTC, phoenixpereira requested changes

2024-12-04 21:19 UTC, phoenixpereira commented on index.html
> +			content="MyTimetable is a simple drag-and-drop timetable planner for University of Adelaide students."
The meta description should be about 150-220 characters, so maybe something like "MyTimetable is a simple drag-and-drop timetable planner for University of Adelaide students. Easily organise your course classes and create the perfect timetable with this tool by the CS Club Open Source Team."

2024-12-05 13:45 UTC, rayokamoto approved these changes
LGTM

2024-12-05 20:44 UTC, phoenixpereira requested changes

2024-12-05 20:44 UTC, phoenixpereira commented on index.html
> +			content="MyTimetable is a simple drag-and-drop timetable planner for University of Adelaide students. Easily organise your course classes and create the perfect timetable with this tool by the CS
The longer description was just needed for the top meta description, the og and twitter descriptions have lower character limits, so make them just use the first sentence.

2024-12-08 07:48 UTC, phoenixpereira approved these changes

2024-12-08 07:48 UTC, merged