feat: Add ready and copy text buttons
compsci-adl/mytimetable pull request #34
Opened 2024-12-07 03:14 UTC by jsun969

### Description
*Briefly describe the purpose of this pull request.*

### Changes Made
*Provide a list of changes made in this pull request.*

### Related Issues
*Reference any related issues using keywords like "Fixes #issue-number".*

### Additional Notes
*Add any other notes or screenshots that might be helpful for the reviewers.*

2024-12-07 06:02 UTC, phoenixpereira requested changes

2024-12-07 06:02 UTC, phoenixpereira commented on src/components/Calendar.tsx
> +		</div>
The ready for enrolment button should be hidden if you haven't added any courses yet.

2024-12-07 06:02 UTC, phoenixpereira commented on src/components/Calendar.tsx
> +			</Tooltip>
It makes more sense to have the copy to clipboard button within the enrollment modal in the bottom left.

2024-12-07 06:02 UTC, phoenixpereira commented on src/components/EnrolmentModal.tsx
> +				</ModalBody>
Add a sentence here saying, "Copy the numbers provided below and enter them on the enrollment page of Access Adelaide to register for the classes."

2024-12-07 06:02 UTC, phoenixpereira commented on src/components/EnrolmentModal.tsx
> +							</CardBody>
Should indicate which one is the enrolment class and which ones are related classes since you need this information when enrolling in Access Adelaide.

2024-12-07 12:32 UTC, jsun969 commented on src/components/EnrolmentModal.tsx
> +							</CardBody>
that's kinda overcomplicated for enrolling, I'd rather get rid of that

2024-12-07 12:57 UTC, jsun969 commented on src/components/EnrolmentModal.tsx
> +				</ModalBody>
nah user need to select the course instead of copy. and it's in the help modal. it's fine just leave it black for the style as well

2024-12-07 12:58 UTC, jsun969 commented on src/components/Calendar.tsx
> +			</Tooltip>
copy is a functionality for sharing so we'd better keep it outside the "ready" button

2024-12-08 03:31 UTC, phoenixpereira approved these changes

2024-12-08 03:31 UTC, merged