TikTok and YouTube Link
compsci-adl/mytimetable pull request #42
Opened 2024-12-28 10:20 UTC by shxhid01

### Description
Added TikTok and YouTube links to footer

### Changes Made
N/A

### Related Issues
N/A

### Additional Notes
N/A

2024-12-28 10:38 UTC, phoenixpereira requested changes

2024-12-28 10:38 UTC, phoenixpereira commented on src/components/Footer.tsx
Can you make the links have the same order as the CS Club website? 

![image](https://github.com/user-attachments/assets/1cb0a8ea-1169-4211-a860-38f5874a7df6)

2024-12-28 16:12 UTC, shxhid01 commented on src/components/Footer.tsx
yep

2024-12-30 00:27 UTC, phoenixpereira approved these changes

2024-12-30 00:30 UTC, phoenixpereira requested changes

2024-12-30 00:30 UTC, phoenixpereira commented on src/components/Footer.tsx
> +	Link,
Remove this as it's not needed.

2025-01-01 22:11 UTC, phoenixpereira approved these changes

2025-01-01 22:12 UTC, merged

2025-05-29 05:13 UTC, vggj21 reviewed
D